# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba2af32210f3fac5310a39c09ad97fc5b1b387167bdfefbcd1753edbcfb9ace9a24efd247c7d48937b79dc0725d8226b1e4a8a7a1f2cf5214c8ee6aa4bf556dd

test:
  secret_key_base: e735a90aefc04fbb8288ec0108567247fe9e66e9595c028563d7041ef0de6f6bd527838af801364307fa66e673c04162e65cbad849e6e25b0ab4d4c24ca76ad3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
